# Lists

In [2]:
#Slicicng
phrase = ['Astra', 'inclinant', 'sed', 'non', 'obligant']
print(phrase[:3])
print(phrase[3:])

['Astra', 'inclinant', 'sed']
['non', 'obligant']


In [3]:
#List method append
my_list = [0, 1, 1, 2, 3]
variable = 5
my_list.append(variable)
print(my_list)

[0, 1, 1, 2, 3, 5]


In [4]:
# insert
my_list = ['a', 'b', 'd']
my_list.insert(2, 'c')
print(my_list)

['a', 'b', 'c', 'd']


In [5]:
#Remove
my_list = ['a', 'b', 'd', 'a']
my_list.remove('a')
print(my_list)

['b', 'd', 'a']


In [6]:
#pop
my_list = ['a', 'b', 'c']
print(my_list.pop())
print(my_list)

c
['a', 'b']


In [7]:
#clear
my_list = ['a', 'b', 'c']
my_list.clear()
print(my_list)

[]


In [8]:
#index()
#Return the index of the first occurrence of an item in the list:
my_list = ['a', 'b', 'c', 'a']
my_list.index('a')

0

In [9]:
#count()
#Return the number of times an item occurs in the list:
my_list = ['a', 'b', 'c', 'a']
my_list.count('a')

2

In [10]:
#sort()
#Sorts the list ascending by default. You can also make a function to decide the sorting criteria:
char_list = ['b', 'c', 'a']
num_list = [2, 3, 1]
char_list.sort()
num_list.sort(reverse=True)
print(char_list)
print(num_list)

['a', 'b', 'c']
[3, 2, 1]


# Tuples (unpacking)

In [22]:
def to_dollars_cents(price):
    ''' 
    Split price into dollars and cents
    '''
    dollars = int (price // 1 ) 
    cents = round ((price % 1 ) * 100)
    return dollars, cents

In [23]:
to_dollars_cents( 7.99)

(7, 99)

In [26]:
dollar , cent = to_dollars_cents( 10.59)
print(dollar)
print(cent)

10
59


In [27]:
#Unpack the tuple extract name and player position
team = [
    ('Marta', 20, 'center'),
    ('Karthika', 30, 'point guard'),
    ('Sanjan', 7, 'power forward'),
    ('Mithran', 4, 'small forward'),
    ('Murali', 32, 'shooting guard')
]

In [47]:
def player_position(players):
    result = []
    for name, age, position in players:
        result.append('Name: {:>20} \nPosition: {:>16}\n'.format(name,position))

    return result
        

In [48]:
for player in player_position(team):
    print(player)

Name:                Marta 
Position:           center

Name:             Karthika 
Position:      point guard

Name:               Sanjan 
Position:    power forward

Name:              Mithran 
Position:    small forward

Name:               Murali 
Position:   shooting guard



In [58]:

for left in range(7):
    for right in range(left, 7):
        print(f"[{left}|{right}]", end=" ")
    print('\n')

[0|0] [0|1] [0|2] [0|3] [0|4] [0|5] [0|6] 

[1|1] [1|2] [1|3] [1|4] [1|5] [1|6] 

[2|2] [2|3] [2|4] [2|5] [2|6] 

[3|3] [3|4] [3|5] [3|6] 

[4|4] [4|5] [4|6] 

[5|5] [5|6] 

[6|6] 



In [63]:
dominoes = []
for left in range(7):
    for right in range(left, 7):
        dominoes.append((left, right))

dominoes

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (0, 5),
 (0, 6),
 (1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 4),
 (4, 5),
 (4, 6),
 (5, 5),
 (5, 6),
 (6, 6)]

In [81]:
pips_from_loop = []
for domino in dominoes:
    pips_from_loop.append(domino[0] + domino[1])

pips_from_loop

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 2,
 3,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 8,
 6,
 7,
 8,
 9,
 8,
 9,
 10,
 10,
 11,
 12]

In [80]:
pips_from_loop_comp = []
pips_from_loop_comp = [domino[0] + domino[1] for domino in dominoes]
print(pips_from_loop_comp)

[0, 1, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 7, 4, 5, 6, 7, 8, 6, 7, 8, 9, 8, 9, 10, 10, 11, 12]


In [82]:
# Zip
cities = ['Paris', 'Lagos', 'Mumbai']
countries = ['France', 'Nigeria', 'India']
places = zip(cities, countries)
print(places)
print(list(places))

[('Paris', 'France'), ('Lagos', 'Nigeria'), ('Mumbai', 'India')]


In [83]:
#Unzip
scientists = [('Nikola', 'Tesla'), ('Charles', 'Darwin'), ('Marie', 'Curie')]
given_names, surnames = zip(*scientists)
print(given_names)
print(surnames)

('Nikola', 'Charles', 'Marie')
('Tesla', 'Darwin', 'Curie')


In [84]:
#enumerate
letters = ['a', 'b', 'c']
for index, letter in enumerate(letters):
   print(index, letter)

0 a
1 b
2 c


In [86]:
#dictionaries
zoo = {
    'animal_1' : 'Zebra' ,
    'animal_2' : 'Lion' ,
    'animal_3' : 'Tiger'  
}

In [88]:
zoo['animal_3']

'Tiger'

In [90]:
zoo = dict(
    animal_1 = 'Zebra' ,
    animal_2 = 'Lion' ,
    animal_3 = 'Tiger'  
)

In [91]:
zoo['animal_3']

'Tiger'

In [92]:
# assign new value
zoo['animal_4'] = 'Leopard'

In [93]:
zoo['animal_4']

'Leopard'

# Convert tuple into dictionary

In [98]:
team = [
    ('Marta', 20, 'center'),
    ('Karthika', 30, 'point guard'),
    ('Sanjan', 7, 'power forward'),
    ('Mithran', 4, 'small forward'),
    ('Murali', 32, 'shooting guard'),
    ('Lucy', 20, 'center'),
    ('Violet', 30, 'point guard'),
    ('Alex', 7, 'power forward'),
    ('Chase', 4, 'small forward'),
    ('Luca', 32, 'shooting guard')
]

new_team = {}
for name,age,position in team:
    if position in new_team:
        new_team[position].append((name,age))
    else:
        new_team[position] = [(name, age)]

In [95]:
new_team

{'center': [('Marta', 20), ('Lucy', 20)],
 'point guard': [('Karthika', 30), ('Violet', 30)],
 'power forward': [('Sanjan', 7), ('Alex', 7)],
 'small forward': [('Mithran', 4), ('Chase', 4)],
 'shooting guard': [('Murali', 32), ('Luca', 32)]}

In [102]:
new_team.keys()

dict_keys(['center', 'point guard', 'power forward', 'small forward', 'shooting guard'])

In [103]:
new_team.values()

dict_values([[('Marta', 20), ('Lucy', 20)], [('Karthika', 30), ('Violet', 30)], [('Sanjan', 7), ('Alex', 7)], [('Mithran', 4), ('Chase', 4)], [('Murali', 32), ('Luca', 32)]])

In [104]:
new_team.items()

dict_items([('center', [('Marta', 20), ('Lucy', 20)]), ('point guard', [('Karthika', 30), ('Violet', 30)]), ('power forward', [('Sanjan', 7), ('Alex', 7)]), ('small forward', [('Mithran', 4), ('Chase', 4)]), ('shooting guard', [('Murali', 32), ('Luca', 32)])])

In [105]:
for a,b in new_team.items():
    print(a,b)

center [('Marta', 20), ('Lucy', 20)]
point guard [('Karthika', 30), ('Violet', 30)]
power forward [('Sanjan', 7), ('Alex', 7)]
small forward [('Mithran', 4), ('Chase', 4)]
shooting guard [('Murali', 32), ('Luca', 32)]


# sets

In [107]:
x = set(('food', 'good', 'great', 'food'))
print(x)

{'food', 'great', 'good'}


In [108]:
x = set(['food', 'good', 'great', 'food'])
print(x)

{'food', 'great', 'good'}


In [109]:
x = set('food')
print(x)

{'d', 'f', 'o'}


In [112]:
# below one throws error because each element of a set must be hashable (≈ immutable), but {‘a’, ‘b’, ‘c’} is a set, which is a mutable 
example_c = [1.5, {'a', 'b', 'c'}, 1.5]
set(example_c)

<class 'TypeError'>: unhashable type: 'set'

In [113]:
#example demonstrates the add() method, which is one of the special methods available to sets but not to frozensets. 
example_d = {'mother', 'hamster', 'father'}
example_d.add('elder')
example_d

{'elder', 'father', 'hamster', 'mother'}

In [ ]:
example_e = [1.5, frozenset(['a', 'b', 'c']), 1.5]
set(example_e)

In [111]:
#intersection
set1 = {1, 2, 3, 4, 5, 6}
set2 = {2, 3, 6, 7, 8}
print(set1.intersection(set2))
print(set1 & set2)

{2, 3, 6}
{2, 3, 6}


In [115]:
# union
set_1 = {'a', 'b', 'c'}
set_2 = {'b', 'c', 'd'}
set_1.union(set_2)
set_1 | set_2

{'a', 'b', 'c', 'd'}

In [117]:
#difference
print(set_1.difference(set_2))
print(set_1 - set_2)
print(set_1.symmetric_difference(set_2))
print(set_1 ^ set_2)

{'a'}
{'a'}
{'a', 'd'}
{'a', 'd'}


## Numpy

In [150]:
import numpy as np
list_1 = [1,2,3]
list_2 = [4,5,6]
array_1 = np.array(list_1)
array_2 = np.array(list_2)
array_3 = array_1 * array_2

In [122]:
array_3
print(type(array_3))
array_3.dtype

<class 'numpy.ndarray'>


dtype('int32')

In [120]:
print(np.__version__)

2.3.5


In [142]:
#Array attributes
'''ndarray.shape: returns a tuple of the array’s dimensions
ndarray.dtype: returns the data type of the array’s contents
ndarray.size: returns the total number of elements in the array
ndarray.T: returns the array transposed (rows become columns, columns become rows) '''
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d.shape)
print(array_2d.dtype)
print(array_2d.size)
print(array_2d.T)



(2, 3)
int32
6
[[1 4]
 [2 5]
 [3 6]]


In [125]:
array_3.ndim

1

In [127]:
#1-D array:
array_1d = np.array([1, 2, 3])
array_1d


array([1, 2, 3])

In [128]:
#2-D array:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
array_2d


array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array_3d


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [130]:
#Creates an array of a designated shape that is pre-filled with zeros:
np.zeros((3, 2))


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [131]:
#Creates an array of a designated shape that is pre-filled with ones:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [132]:
#Creates an array of a designated shape that is pre-filled with a specified value:
np.full((5, 3), 8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [133]:
#Returns a copy of the array collapsed into one dimension
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
array_2d.flatten()


array([1, 2, 3, 4, 5, 6])

In [134]:
#Gives a new shape to an array without changing its data
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
array_2d.reshape(3, 2)



array([[1, 2],
       [3, 4],
       [5, 6]])

In [139]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
array_2d.reshape(3, -1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [140]:
#Converts an array to a list object. Multidimensional arrays are converted to nested lists. 
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
array_2d.tolist()


[[1, 2, 3], [4, 5, 6]]

In [141]:
#Math Function
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a.max())
print(a.mean())
print(a.min())
print(a.std())

6
3.5
1
1.707825127659933


In [146]:
#Indexing
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a[0])
print(a[1])
print(a[0, 1])
print(a[1, 2])
# Slicing
a[:, 1:]

[1 2 3]
[4 5 6]
2
6


array([[2, 3],
       [5, 6]])

In [147]:
#  you cannot lengthen or shorten the array:

a = np.array([1, 2, 3])
a[3] = 100

<class 'IndexError'>: index 3 is out of bounds for axis 0 with size 3

# Pandas

In [152]:
!mamba install pandas

mambajs 0.19.7

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge, conda-forge

Solving environment...
Solving took 4.4235 seconds
  Name                          Version                       Build                         Channel                       
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
+ pandas                        2.3.3                         np22py313h9d9dc1e_0           emscripten-forge              
+ python-tzdata                 2025.3                        pyhd8ed1ab_0                  conda-forge                   
- pip                           25.3                          pyh145f28c_0                  conda-forge                   


In [153]:
import pandas as pd
#creating data frame from dictionary
data1 = {'col1' : [1,2], 'col2': [3,4]}
df = pd.DataFrame(data=data1)
df

col1  col2
0     1     3
1     2     4

In [154]:
#creating data frame from np array
df2 = pd.DataFrame(np.array([[1,2,3],[4,5,6],[7,8,9]]),
                columns = ['a', 'b', 'c'], index = ['x', 'y', 'z'])
df2

a  b  c
x  1  2  3
y  4  5  6
z  7  8  9

In [155]:
df2 = pd.DataFrame(np.array([[1,2,3],[4,5,6],[7,8,9]]))
               
df2

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
import os
os.listdir('/drive')

In [2]:
# read the csv file
df3 = pd.read_csv("drive/titanic.csv") 
df3.head()

<class 'NameError'>: name 'pd' is not defined

In [180]:
# print class of first row
print(type(df3.iloc[0]))
# print class of name column
print(type(df3['Name']))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>


In [183]:
titanic = df3

In [184]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [185]:
titanic.shape

(418, 12)

In [186]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   Name         418 non-null    object 
 4   Sex          418 non-null    object 
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64  
 7   Parch        418 non-null    int64  
 8   Ticket       418 non-null    object 
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object 
 11  Embarked     418 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 31.1+ KB


In [188]:
titanic['Name']

0                                  Kelly, Mr. James
1                  Wilkes, Mrs. James (Ellen Needs)
2                         Myles, Mr. Thomas Francis
3                                  Wirz, Mr. Albert
4      Hirvonen, Mrs. Alexander (Helga E Lindqvist)
                           ...                     
413                              Spector, Mr. Woolf
414                    Oliva y Ocana, Dona. Fermina
415                    Saether, Mr. Simon Sivertsen
416                             Ware, Mr. Frederick
417                        Peter, Master. Michael J
Name: Name, Length: 418, dtype: object

In [189]:
titanic.Name

0                                  Kelly, Mr. James
1                  Wilkes, Mrs. James (Ellen Needs)
2                         Myles, Mr. Thomas Francis
3                                  Wirz, Mr. Albert
4      Hirvonen, Mrs. Alexander (Helga E Lindqvist)
                           ...                     
413                              Spector, Mr. Woolf
414                    Oliva y Ocana, Dona. Fermina
415                    Saether, Mr. Simon Sivertsen
416                             Ware, Mr. Frederick
417                        Peter, Master. Michael J
Name: Name, Length: 418, dtype: object

In [192]:
titanic[['Name','Age']]

Name   Age
0                                Kelly, Mr. James  34.5
1                Wilkes, Mrs. James (Ellen Needs)  47.0
2                       Myles, Mr. Thomas Francis  62.0
3                                Wirz, Mr. Albert  27.0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  22.0
..                                            ...   ...
413                            Spector, Mr. Woolf   NaN
414                  Oliva y Ocana, Dona. Fermina  39.0
415                  Saether, Mr. Simon Sivertsen  38.5
416                           Ware, Mr. Frederick   NaN
417                      Peter, Master. Michael J   NaN

[418 rows x 2 columns]

In [193]:
# iLOC
titanic.iloc[0]

PassengerId                 892
Survived                      0
Pclass                        3
Name           Kelly, Mr. James
Sex                        male
Age                        34.5
SibSp                         0
Parch                         0
Ticket                   330911
Fare                     7.8292
Cabin                       NaN
Embarked                      Q
Name: 0, dtype: object

In [194]:
titanic.iloc[[0]]

PassengerId  Survived  Pclass              Name   Sex   Age  SibSp  Parch  \
0          892         0       3  Kelly, Mr. James  male  34.5      0      0   

   Ticket    Fare Cabin Embarked  
0  330911  7.8292   NaN        Q

In [196]:
titanic.iloc[0:3]

PassengerId  Survived  Pclass                              Name     Sex  \
0          892         0       3                  Kelly, Mr. James    male   
1          893         1       3  Wilkes, Mrs. James (Ellen Needs)  female   
2          894         0       2         Myles, Mr. Thomas Francis    male   

    Age  SibSp  Parch  Ticket    Fare Cabin Embarked  
0  34.5      0      0  330911  7.8292   NaN        Q  
1  47.0      1      0  363272  7.0000   NaN        S  
2  62.0      0      0  240276  9.6875   NaN        Q

In [197]:
#Accesses a group of rows and columns using integer-based indexing
titanic.iloc[0:3 ,[3,4]]

Name     Sex
0                  Kelly, Mr. James    male
1  Wilkes, Mrs. James (Ellen Needs)  female
2         Myles, Mr. Thomas Francis    male

In [200]:
#LOC Accesses a group of rows and columns by label(s)
titanic.loc[0:3 ,['Name']]

Name
0                  Kelly, Mr. James
1  Wilkes, Mrs. James (Ellen Needs)
2         Myles, Mr. Thomas Francis
3                  Wirz, Mr. Albert

In [201]:
# create new column
titanic['Age_plus_100'] = titanic['Age'] + 100
titanic.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  Age_plus_100  
0   330911   7.8292   NaN        Q         134.5  
1   363272   7.0000   NaN        S         147.0  
2   240276   9.6875   NaN        Q         162.0  
3   315154   8.6625   NaN        S         127.0  
4  3101298  12.2875   NaN        S         122.0

In [202]:
df = pd.DataFrame({
   'A': ['alpha', 'apple', 'arsenic', 'angel', 'android'],
   'B': [1, 2, 3, 4, 5],
   'C': ['coconut', 'curse', 'cassava', 'cuckoo', 'clarinet'],
   'D': [6, 7, 8, 9, 10]
   },
   index=['row_0', 'row_1', 'row_2', 'row_3', 'row_4'])
df

A  B         C   D
row_0    alpha  1   coconut   6
row_1    apple  2     curse   7
row_2  arsenic  3   cassava   8
row_3    angel  4    cuckoo   9
row_4  android  5  clarinet  10

In [203]:
#Inserting the row index name as a list returns a DataFrame object:
print(df.loc[['row_1']])

           A  B      C  D
row_1  apple  2  curse  7


In [204]:
#Inserting just the row index name in selector brackets returns a Series object.
print(df.loc['row_1'])

A    apple
B        2
C    curse
D        7
Name: row_1, dtype: object


In [209]:
print(df.loc['row_2'])

A    arsenic
B          3
C    cassava
D          8
Name: row_2, dtype: object


In [214]:
df.loc[['row_2','row_3']]

A  B        C  D
row_2  arsenic  3  cassava  8
row_3    angel  4   cuckoo  9

In [216]:
df.loc['row_2':'row_3']

A  B        C  D
row_2  arsenic  3  cassava  8
row_3    angel  4   cuckoo  9

In [217]:
df.iloc[1]

A    apple
B        2
C    curse
D        7
Name: row_1, dtype: object

In [222]:
#To select multiple rows by index number, use a list within selector brackets:
df.iloc[[1,2,3]]


A  B        C  D
row_1    apple  2    curse  7
row_2  arsenic  3  cassava  8
row_3    angel  4   cuckoo  9

In [223]:
#Specify a range of rows by index number:
df.iloc[1:3]

A  B        C  D
row_1    apple  2    curse  7
row_2  arsenic  3  cassava  8

In [225]:
#column selection using bracket
print(df['C'])

row_0     coconut
row_1       curse
row_2     cassava
row_3      cuckoo
row_4    clarinet
Name: C, dtype: object


In [227]:
#column selection using '.' dot notation
df.C

row_0     coconut
row_1       curse
row_2     cassava
row_3      cuckoo
row_4    clarinet
Name: C, dtype: object

In [229]:
df.loc[:,['A','D']]

A   D
row_0    alpha   6
row_1    apple   7
row_2  arsenic   8
row_3    angel   9
row_4  android  10

In [231]:
#Both loc[] and iloc[] can be used to select specific rows and columns together. 
df.loc['row_2':'row_4',['A','C']]

A         C
row_2  arsenic   cassava
row_3    angel    cuckoo
row_4  android  clarinet

In [234]:
#rows and column index based
df.iloc[[0,2],[0,3]]

A  D
row_0    alpha  6
row_2  arsenic  8

In [235]:
df = pd.DataFrame({
   'A': ['alpha', 'apple', 'arsenic', 'angel', 'android'],
   'B': [1, 2, 3, 4, 5],
   'C': ['coconut', 'curse', 'cassava', 'cuckoo', 'clarinet'],
   'D': [6, 7, 8, 9, 10]
   },
   )
df

A  B         C   D
0    alpha  1   coconut   6
1    apple  2     curse   7
2  arsenic  3   cassava   8
3    angel  4    cuckoo   9
4  android  5  clarinet  10

In [236]:
df.loc[0:3,'C']

0    coconut
1      curse
2    cassava
3     cuckoo
Name: C, dtype: object

In [273]:
#builds the dataframe you described and then creates the boolean mask for planets with fewer than 20 moons.
import pandas as pd
import numpy as np

data = {
    'Planet': ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune'],
    'Radius_km': [2439, 6051, 6371, 3389, 69911, 58232, 25362, 24622],
    'Moons': [0, 0, 1, 2, 80, 83, 27, 14],
    'Type': ['Terrestrial', 'Terrestrial', 'Terrestrial', 'Terrestrial',
             'Gas Giant', 'Gas Giant', 'Ice Giant', 'Ice Giant'],
    'Has_Rings': [False, False, False, False, True, True, True, True],
    'Avg_Temp_C': [167, 464, 15, -65, -110, -140, -195, -200],
    'Magnetic_Field': [True, False, True, Weak := False, True, True, True, True]
}

planets_df = pd.DataFrame(data)
planets_df



Planet  Radius_km  Moons         Type  Has_Rings  Avg_Temp_C  \
0  Mercury       2439      0  Terrestrial      False         167   
1    Venus       6051      0  Terrestrial      False         464   
2    Earth       6371      1  Terrestrial      False          15   
3     Mars       3389      2  Terrestrial      False         -65   
4  Jupiter      69911     80    Gas Giant       True        -110   
5   Saturn      58232     83    Gas Giant       True        -140   
6   Uranus      25362     27    Ice Giant       True        -195   
7  Neptune      24622     14    Ice Giant       True        -200   

   Magnetic_Field  
0            True  
1           False  
2            True  
3           False  
4            True  
5            True  
6            True  
7            True

In [262]:
mask = planets_df['Moons'] < 20
mask

0     True
1     True
2     True
3     True
4    False
5    False
6    False
7     True
Name: Moons, dtype: bool

In [245]:
planets_df[planets_df['Moons'] < 20]

Planet  Radius_km  Moons
0  Mercury       2439      0
1    Venus       6051      0
2    Earth       6371      1
3     Mars       3389      2
7  Neptune      24622     14

In [263]:
mask = (planets_df['Moons'] < 10) | (planets_df['Moons'] > 50)

In [264]:
planets_df[mask]

Planet  Radius_km  Moons
0  Mercury       2439      0
1    Venus       6051      0
2    Earth       6371      1
3     Mars       3389      2
4  Jupiter      69911     80
5   Saturn      58232     83

In [268]:
#select all planets that have more than 20 moons, 
#but not planets with 80 moons and not planets with a radius less than 50,000 kilometers.
mask = (planets_df['Moons'] > 20) & ~(planets_df['Moons'] == 80) & ~(planets_df['Radius_km'] < 50000)

In [269]:
planets_df[mask]

Planet  Radius_km  Moons
5  Saturn      58232     83

In [278]:
#groupby
planets_df.groupby(['Type']).sum(numeric_only=True)

Radius_km  Moons  Has_Rings  Avg_Temp_C  Magnetic_Field
Type                                                                
Gas Giant       128143    163          2        -250               2
Ice Giant        49984     41          2        -395               2
Terrestrial      18250      3          0         581               2

In [285]:
print(planets_df.columns)
print(planets_df.dtypes)

Index(['Planet', 'Radius_km', 'Moons', 'Type', 'Has_Rings', 'Avg_Temp_C',
       'Magnetic_Field'],
      dtype='object')
Planet            object
Radius_km          int64
Moons              int64
Type              object
Has_Rings           bool
Avg_Temp_C         int64
Magnetic_Field      bool
dtype: object


In [282]:
planets_df.groupby(['Type']).sum()[['Moons']]

Moons
Type              
Gas Giant      163
Ice Giant       41
Terrestrial      3

In [289]:
planets_df.groupby(['Type','Moons']).mean(numeric_only=True)


Radius_km  Has_Rings  Avg_Temp_C  Magnetic_Field
Type        Moons                                                  
Gas Giant   80       69911.0        1.0      -110.0             1.0
            83       58232.0        1.0      -140.0             1.0
Ice Giant   14       24622.0        1.0      -200.0             1.0
            27       25362.0        1.0      -195.0             1.0
Terrestrial 0         4245.0        0.0       315.5             0.5
            1         6371.0        0.0        15.0             1.0
            2         3389.0        0.0       -65.0             0.0

In [290]:
planets_df.groupby(['Type','Moons'])[['Radius_km','Avg_Temp_C','Moons']].agg(['mean','max'])

Radius_km        Avg_Temp_C      Moons    
                       mean    max       mean  max  mean max
Type        Moons                                           
Gas Giant   80      69911.0  69911     -110.0 -110  80.0  80
            83      58232.0  58232     -140.0 -140  83.0  83
Ice Giant   14      24622.0  24622     -200.0 -200  14.0  14
            27      25362.0  25362     -195.0 -195  27.0  27
Terrestrial 0        4245.0   6051      315.5  464   0.0   0
            1        6371.0   6371       15.0   15   1.0   1
            2        3389.0   3389      -65.0  -65   2.0   2

In [291]:
# to get 90th percentile of each group

def percentile_90(x):
    return x.quantile(0.9)



In [293]:
#call fn in aggregation
planets_df.groupby(['Type','Magnetic_Field'])[['Radius_km','Avg_Temp_C','Moons']].agg(['mean',percentile_90])

Radius_km               Avg_Temp_C                \
                                mean percentile_90       mean percentile_90   
Type        Magnetic_Field                                                    
Gas Giant   True             64071.5       68743.1     -125.0        -113.0   
Ice Giant   True             24992.0       25288.0     -197.5        -195.5   
Terrestrial False             4720.0        5784.8      199.5         411.1   
            True              4405.0        5977.8       91.0         151.8   

                           Moons                
                            mean percentile_90  
Type        Magnetic_Field                      
Gas Giant   True            81.5          82.7  
Ice Giant   True            20.5          25.7  
Terrestrial False            1.0           1.8  
            True             0.5           0.9

In [294]:
clothes = pd.DataFrame({'type': ['pants', 'shirt', 'shirt', 'pants', 'shirt', 'pants'],
                       'color': ['red', 'blue', 'green', 'blue', 'green', 'red'],
                       'price_usd': [20, 35, 50, 40, 100, 75],
                       'mass_g': [125, 440, 680, 200, 395, 485]})

In [295]:
clothes

type  color  price_usd  mass_g
0  pants    red         20     125
1  shirt   blue         35     440
2  shirt  green         50     680
3  pants   blue         40     200
4  shirt  green        100     395
5  pants    red         75     485

In [297]:
clothes.groupby('type').mean(numeric_only=True)

price_usd  mass_g
type                    
pants  45.000000   270.0
shirt  61.666667   505.0

In [299]:
#groups may be created based on multiple columns:
clothes.groupby(['type', 'color']).min(numeric_only=True)

price_usd  mass_g
type  color                   
pants blue          40     200
      red           20     125
shirt blue          35     440
      green         50     395

In [300]:
#To simply return the number of observations there are in each group, use the size() method. 
clothes.groupby(['type', 'color']).size()

type   color
pants  blue     1
       red      2
shirt  blue     1
       green    2
dtype: int64

In [305]:
#applies the sum() and mean() functions to the price and mass_g columns of the clothes dataframe.
clothes[['price_usd', 'mass_g']].agg(['sum', 'mean'])


price_usd  mass_g
sum   320.000000  2325.0
mean   53.333333   387.5

In [313]:
#functions across axis 1. In other words, instead of applying the functions down each column, they’re applied over each row.
clothes[['price_usd', 'mass_g']].agg(['sum', 'mean'], axis = 1)

sum   mean
0  145.0   72.5
1  475.0  237.5
2  730.0  365.0
3  240.0  120.0
4  495.0  247.5
5  560.0  280.0

In [310]:
#different functions are applied to different columns.
clothes[['price_usd', 'mass_g']].agg({'price_usd': 'sum', 
                                      'mass_g' : ['mean', 'median']}
                                    )

price_usd  mass_g
sum         320.0     NaN
mean          NaN   387.5
median        NaN   417.5

In [311]:
clothes.agg({'price_usd': 'sum', 
            'mass_g' : ['mean', 'median']}
            )

price_usd  mass_g
sum         320.0     NaN
mean          NaN   387.5
median        NaN   417.5

In [315]:
#groupby and agg together
grouped = clothes.groupby('color').agg({'price_usd': 'sum', 
            'mass_g' : ['mean', 'median']}
            )

In [316]:
grouped

price_usd mass_g       
            sum   mean median
color                        
blue         75  320.0  320.0
green       150  537.5  537.5
red          95  305.0  305.0

In [318]:
grouped.index

Index(['blue', 'green', 'red'], dtype='object', name='color')

In [319]:
grouped = clothes.groupby(['color', 'type']).agg(['mean', 'min'])

In [321]:
grouped

price_usd     mass_g     
                 mean min   mean  min
color type                           
blue  pants      40.0  40  200.0  200
      shirt      35.0  35  440.0  440
green shirt      75.0  50  537.5  395
red   pants      47.5  20  305.0  125

In [320]:
grouped.index

MultiIndex([( 'blue', 'pants'),
            ( 'blue', 'shirt'),
            ('green', 'shirt'),
            (  'red', 'pants')],
           names=['color', 'type'])

In [322]:
#To select a first-level (top) column:
grouped.loc[:,'price_usd']

mean  min
color type            
blue  pants  40.0   40
      shirt  35.0   35
green shirt  75.0   50
red   pants  47.5   20

In [323]:
#To select a second-level (bottom) column:
grouped.loc[:,('price_usd', 'min')]

color  type 
blue   pants    40
       shirt    35
green  shirt    50
red    pants    20
Name: (price_usd, min), dtype: int64

In [324]:
#To select first-level (left-most) row:
grouped.loc['blue', :]

price_usd     mass_g     
           mean min   mean  min
type                           
pants      40.0  40  200.0  200
shirt      35.0  35  440.0  440

In [325]:
#To select a bottom-level (right-most) row:
grouped.loc['green', :]

price_usd     mass_g     
           mean min   mean  min
type                           
shirt      75.0  50  537.5  395

In [327]:
#select individual values:
grouped.loc[('blue', 'shirt') ,('mass_g', 'mean')]

np.float64(440.0)

In [ ]:
#Joining dataframes

data = {
    'Planet': ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune'],
    'Radius_km': [2439, 6051, 6371, 3389, 69911, 58232, 25362, 24622],
    'Moons': [0, 0, 1, 2, 80, 83, 27, 14],
    'Type': ['Terrestrial', 'Terrestrial', 'Terrestrial', 'Terrestrial',
             'Gas Giant', 'Gas Giant', 'Ice Giant', 'Ice Giant'],
    'Has_Rings': [False, False, False, False, True, True, True, True],
    'Avg_Temp_C': [167, 464, 15, -65, -110, -140, -195, -200],
    'Magnetic_Field': [True, False, True, Weak := False, True, True, True, True]
}


In [328]:
data = {
    'Planet': ['Mercury', 'Venus', 'Earth', 'Mars'],
    'Radius_km': [2439, 6051, 6371, 3389],
    'Moons': [0, 0, 1, 2],
}

df1 = pd.DataFrame(data)
df1


Planet  Radius_km  Moons
0  Mercury       2439      0
1    Venus       6051      0
2    Earth       6371      1
3     Mars       3389      2

In [329]:
data = {
    'Planet': [ 'Jupiter', 'Saturn', 'Uranus', 'Neptune'],
    'Radius_km': [ 69911, 58232, 25362, 24622],
    'Moons': [ 80, 83, 27, 14],

}

df2 = pd.DataFrame(data)
df2

Planet  Radius_km  Moons
0  Jupiter      69911     80
1   Saturn      58232     83
2   Uranus      25362     27
3  Neptune      24622     14

In [331]:
#concat the dataframe by axio 0 horizontally
df3 = pd.concat([df1,df2], axis = 0)
df3

Planet  Radius_km  Moons
0  Mercury       2439      0
1    Venus       6051      0
2    Earth       6371      1
3     Mars       3389      2
0  Jupiter      69911     80
1   Saturn      58232     83
2   Uranus      25362     27
3  Neptune      24622     14

In [334]:
#Reset the index of newly created dataframe
df3 = df3.reset_index(drop = True)
df3

Planet  Radius_km  Moons
0  Mercury       2439      0
1    Venus       6051      0
2    Earth       6371      1
3     Mars       3389      2
4  Jupiter      69911     80
5   Saturn      58232     83
6   Uranus      25362     27
7  Neptune      24622     14

In [339]:
import pandas as pd

df4 = pd.DataFrame({
    'Planet': [
        'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune',
        'Janssen', 'Tadmor'
    ],
    'type': [
        'Terrestrial', 'Terrestrial', 'Gas Giant', 'Gas Giant',
        'Ice Giant', 'Ice Giant',
        'Exoplanet', 'Exoplanet'
    ],
    'rings': [
        False, False, True, True, True, True,
        False, False
    ],
    'mean_temp_c': [
        15, -65, -110, -140, -195, -200,
        1700, -50   # approximate exoplanet values
    ],
    'magnetic_field': [
        True, False, True, True, True, True,
        False, False   # unknown → False by default
    ],
    'life': [
        True, False, False, False, False, False,
        False, False
    ]
})

df4

Planet         type  rings  mean_temp_c  magnetic_field   life
0    Earth  Terrestrial  False           15            True   True
1     Mars  Terrestrial  False          -65           False  False
2  Jupiter    Gas Giant   True         -110            True  False
3   Saturn    Gas Giant   True         -140            True  False
4   Uranus    Ice Giant   True         -195            True  False
5  Neptune    Ice Giant   True         -200            True  False
6  Janssen    Exoplanet  False         1700           False  False
7   Tadmor    Exoplanet  False          -50           False  False

In [343]:
# inner join (planets common in both dataframe)
inner = pd.merge(df3, df4, on = 'Planet', how = 'inner')
inner

Planet  Radius_km  Moons         type  rings  mean_temp_c  magnetic_field  \
0    Earth       6371      1  Terrestrial  False           15            True   
1     Mars       3389      2  Terrestrial  False          -65           False   
2  Jupiter      69911     80    Gas Giant   True         -110            True   
3   Saturn      58232     83    Gas Giant   True         -140            True   
4   Uranus      25362     27    Ice Giant   True         -195            True   
5  Neptune      24622     14    Ice Giant   True         -200            True   

    life  
0   True  
1  False  
2  False  
3  False  
4  False  
5  False

In [344]:
# outer join (all planets  in both dataframe)
outer = pd.merge(df3, df4, on = 'Planet', how = 'outer')
outer

Planet  Radius_km  Moons         type  rings  mean_temp_c magnetic_field  \
0    Earth     6371.0    1.0  Terrestrial  False         15.0           True   
1  Janssen        NaN    NaN    Exoplanet  False       1700.0          False   
2  Jupiter    69911.0   80.0    Gas Giant   True       -110.0           True   
3     Mars     3389.0    2.0  Terrestrial  False        -65.0          False   
4  Mercury     2439.0    0.0          NaN    NaN          NaN            NaN   
5  Neptune    24622.0   14.0    Ice Giant   True       -200.0           True   
6   Saturn    58232.0   83.0    Gas Giant   True       -140.0           True   
7   Tadmor        NaN    NaN    Exoplanet  False        -50.0          False   
8   Uranus    25362.0   27.0    Ice Giant   True       -195.0           True   
9    Venus     6051.0    0.0          NaN    NaN          NaN            NaN   

    life  
0   True  
1  False  
2  False  
3  False  
4    NaN  
5  False  
6  False  
7  False  
8  False  
9    NaN

In [345]:
# left join (all planets  in left dataframe along with corresponding column values in right dataframe)
left = pd.merge(df3, df4, on = 'Planet', how = 'left')
left

Planet  Radius_km  Moons         type  rings  mean_temp_c magnetic_field  \
0  Mercury       2439      0          NaN    NaN          NaN            NaN   
1    Venus       6051      0          NaN    NaN          NaN            NaN   
2    Earth       6371      1  Terrestrial  False         15.0           True   
3     Mars       3389      2  Terrestrial  False        -65.0          False   
4  Jupiter      69911     80    Gas Giant   True       -110.0           True   
5   Saturn      58232     83    Gas Giant   True       -140.0           True   
6   Uranus      25362     27    Ice Giant   True       -195.0           True   
7  Neptune      24622     14    Ice Giant   True       -200.0           True   

    life  
0    NaN  
1    NaN  
2   True  
3  False  
4  False  
5  False  
6  False  
7  False

In [346]:
# Right join 
right = pd.merge(df3, df4, on = 'Planet', how = 'right')
right

Planet  Radius_km  Moons         type  rings  mean_temp_c  magnetic_field  \
0    Earth     6371.0    1.0  Terrestrial  False           15            True   
1     Mars     3389.0    2.0  Terrestrial  False          -65           False   
2  Jupiter    69911.0   80.0    Gas Giant   True         -110            True   
3   Saturn    58232.0   83.0    Gas Giant   True         -140            True   
4   Uranus    25362.0   27.0    Ice Giant   True         -195            True   
5  Neptune    24622.0   14.0    Ice Giant   True         -200            True   
6  Janssen        NaN    NaN    Exoplanet  False         1700           False   
7   Tadmor        NaN    NaN    Exoplanet  False          -50           False   

    life  
0   True  
1  False  
2  False  
3  False  
4  False  
5  False  
6  False  
7  False